#!/bin/sh 
# syntax: scriptname proteinPDBCode complexPDBCode proteinPDBFile complexPDBFile proteinChain ligandChain
# Mode: 
#  application
#     requires just these paramaters: proteinPDBCode,proteinPDBFile (total 2 parameters)
#  test
#     requires proteinPDBCode, complexPDBCode, proteinPDBFIle, complexPDBFile, proteinChainID,ligandChainID
#     (total 6 parameters)
#  env
#     requires proteinPDBCode, proteinPDBFile  "noscale" (3 parameters)

progname=$0
prefix=`dirname \`which $0 \``
case $# in
2) echo "Running in application mode..."
   pPDB=`echo $1|tr "A-Z" "a-z"`
   pFile=$2
   watsFile="$pFile.hits"
   envFile="$pPDB.env"
   sclFile="$pPDB.scl"
   $prefix/bin/allwats $pFile $watsFile
   $prefix/bin/All.EXE -a $pFile $watsFile $pPDB
   # remove non-firstshell waters
      awk '$3!=0{print}' $envFile > tmp.$$
      $prefix/bin/Scale.EXE -a tmp.$$ $sclFile
      /bin/rm tmp.$$
   echo "Done.";;

3) echo "Running in enviro mode..."
   pPDB=`echo $1|tr "A-Z" "a-z"`
   pFile=$2
   watsFile="$pFile.hits"
   if [ $3 -eq "noscale" ]; then
     $prefix/bin/allwats $pFile $watsFile
     $prefix/bin/All.EXE -a $pFile $watsFile $pPDB
     echo "Done."
   fi
   echo "Done";; 

6) echo "Running in test mode..."
   pPDB=`echo $1|tr "A-Z" "a-z"`
   cPDB=`echo $2|tr "A-Z" "a-z"`
   pFile=$3
   cFile=$4
   pChain=$5
   iChain=$6
   watsFile="$pFile.hits"
   envFile="$pPDB.env"
   sclFile="$pPDB.scl"
   $prefix/bin/Nearby.EXE $cFile $pFile $pChain $iChain $cPDB $pPDB
   $prefix/bin/Conswat.EXE $pFile $cFile $pPDB
   $prefix/bin/allwats $pFile $watsFile
   $prefix/bin/All.EXE -t $pFile $watsFile $pPDB
   #remove non-firstshell waters
     awk '$3!=0{print}' $envFile > tmp.$$
     $prefix/bin/Scale.EXE -t tmp.$$ $sclFile
     /bin/rm tmp.$$
   echo "Done.";;
*) echo "Usage:"
   echo "To run in test mode:"
   echo " $0 protPDBCode cplxPDBCode protPDBFile cplxPDBFile  pChainID ligChainID"
   echo " "
   echo "To run in application mode:"
   echo " $0 protPDBCode protPDBFile"
   echo " "
   echo "To run in environment mode:"
   echo " $0 protPDBCode protPDBFile noscale"
   echo " "
   exit
esac

